version: '3.6'

services:
  postgres:
    image: tienpvse/postgis
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD-postgressecret}
      - POSTGRES_DB=${DB_NAME-survey_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - survey_app

volumes:
  postgres_data:
    name: postgres_data
networks:
  survey_app:
    name: survey_app


